### PR TITLE
Validate First 3 Posts

### PR DESCRIPTION
**Pull request by JediKev**
This changes the behavior of Post Validation for the Akismet extension. Currently the system will only check Akismet if the User whom created the Post has no Group. This can be an issue especially when Users are auto-added to groups on Sign-up. This makes it to where the system will check Akismet on the User's first 3 un-approved Posts. If the User has 3 approved Posts the system will not validate their Posts anymore.

### CODE REVIEW

**Comment by matteocontrini** [comment]
The posts count should be already available in the user schema as `discussion_count` and `comment_count`

**Comment by JediKev** [comment]
@matteocontrini 

I saw that variable but it does not include Approved discussions/comments. If a spammer starts more than 3 discussions (that are spam) and I use `discussions_count` they will not be validated even though it's spam as that variable doesn't care about Approved posts. My goal was to check only Approved posts so that we know they are legitimate users. Does that make sense?

I can modify core as well to include a new function and variable that stores approved discussions/posts but that will be two separate pulls and one will have to be merged before the other.

Cheers.

**Comment by datitisev** [comment]
We might want this functionality to be configurable in both the # of posts, and/or use the previous functionality 🤔. It depends on the size of the community, I guess.

Let's wait for other core members to pitch in though.

**Comment by matteocontrini** [comment]
It also depends on what kind of spam one wants to block with this extension. In my experience most spammers are spammers from the very first post. They don't really wait/take time to get a reputation. So this strategy would actually work

**Comment by luceos** [comment]
I agree that it makes more sense for the extension to scan the first N posts instead. As long as admins are ignored.

**Comment by JediKev** [comment]
@luceos 

Okie doke. I'll exclude admins and add a setting in the Akismet extension settings popup that allows you to input the amount of posts to validate. I have a question though, should I allow `0` to be disabled? Or should I only allow `1` and up?

Cheers.

**Comment by JediKev** [comment]
@askvortsov1 

I do apologize but I have had like 0 time to look into this lately. I believe I left off having to research how to make a configurable setting for extensions. It might take a while as I'm not that familiar with building/extending Flarum extensions atm. Needless to say extensions are pretty well documented so it shouldn't be _too_ difficult.

If someone would like to take this on to get it done faster please don't hesitate to do so (I know some people are itching for updates lol).

Cheers.

**Comment by askvortsov1** [comment]
Absolutely no rush, this isn't a priority for at least the next few release cycles, so take as much time as you need! Feel free to reach out for support on https://discuss.flarum.org if you have any questions!

**Comment by clarkwinkelmann** [comment]
There now exists my own extension that does something similar, though only on the Approval side https://github.com/clarkwinkelmann/flarum-ext-first-post-approval

I can confirm, using `comments_count` won't work. You could just spam until you reach the number. Additional database columns would be necessary, just like I did in First Post Approval.

If the goal is to not allow all groups to post unsupervised, how about adding a permission "Bypass Akismet checks". It will default to Admin, and users could customize it to add additional groups.

**Pull request closed without merging**
